### GET request to example server

# Variables
@baseUrl = http://localhost:3333/api

# Health Check
GET {{baseUrl}}/health

###
# @name getRooms
GET {{baseUrl}}/rooms

###
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Room 4",
  "description": "This is a test room"
}

###

@roomId = 91bc4538-2c70-47f8-9b89-76fcdda8af16

###
# GET request to retrieve a specific room by ID

GET {{baseUrl}}/rooms/{{roomId}}/questions

###
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "What is the capital of France?"
}

###

@questionId = 3cf5bf17-3adb-47f0-b49f-3710834c27c8